# Generated by Django 6.0.1 on 2026-02-05 10:01

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=core.models.generer_code, max_length=20, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('lieuRetrait', models.CharField(max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True, verbose_name='année')),
                ('is_active', models.BooleanField(default=True, verbose_name=' Editions actuelle ?')),
                ('date_event', models.DateField(verbose_name="Date de l'evenement")),
                ('heure_debut', models.TimeField(default='08:00', verbose_name='heure de début')),
                ('heure_fin', models.TimeField(default='22:00', verbose_name='heure de fin')),
                ('map_iframe_url', models.URLField(blank=True, max_length=500, verbose_name='url de google maps')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activite', to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt_text', models.CharField(default='ambiance poro run', max_length=200)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(upload_to='kits')),
                ('avantage', models.TextField(help_text='Liste des avantages separées par des virgules')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(help_text='EX: Or, Platine, Bronze', max_length=20)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaire', to='core.edition')),
            ],
        ),
    ]
